# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.2.0"
require 'yaml'
dir = File.dirname(File.expand_path(__FILE__))
settings = YAML::load_file("#{dir}/env.yml")
Vagrant.configure(2) do |config|
  config.vm.provision "shell", path: "scripts/install.sh",:args => [settings["VM"]["ip"], settings["VM"]["hostname"],settings["VM"]["vmname"],settings["VM"]["password"]]
  config.vm.define settings["VM"]["vmname"] do |client|
    client.vm.box = "ubuntu/bionic64"
    client.vm.hostname = settings["VM"]["hostname"]
	  client.vm.network "private_network", ip: settings["VM"]["ip"]
    client.vm.provider "virtualbox" do |v|
      v.cpus = settings["VM"]["cpus"]
      v.name = settings["VM"]["vmname"]
      v.memory = settings["VM"]["memory"]
    end
     client.vm.provision "shell", path: "eksctl/install.sh"
     client.vm.provision "shell", path: "kubectl/install.sh",:args => [settings["kubectl"]["version"]]
     client.vm.provision "shell", path: "terraform/install.sh",:args => [settings["terraform"]["version"]]
     client.vm.provision "shell", path: "aws-iam-authenticator/install.sh",:args => [settings["aws-iam-authenticator"]["version"]]
     client.vm.provision "shell", path: "awscli/install.sh"
     client.vm.provision "shell", path: "helm/install.sh",:args => [settings["helm"]["version"]]
 end
 end
 